### ISSUE TITLE
can't record audio 

### ISSUE THREAD

**Issue by salmanfarisvp** [SeeedDocument/ReSpeaker-4-Mic-Array-for-Raspberry-Pi#2]
Am using ReSpeaker 4 Mic , Installed all the driver as described in [here](https://github.com/SeeedDocument/ReSpeaker-4-Mic-Array-for-Raspberry-Pi/blob/master/ReSpeaker-4-Mic-Array-for-Raspberry-Pi.md) , and on-board led's are working perfectly . 

while playing the recorded audio using` arecord -Dac108 -f S32_LE -r 16000 -c 4 hello.wav `, 

`aplay hello.wav`
```
laying WAVE 'hello.wav' : Signed 32 bit Little Endian, Rate 16000 Hz, Channels 4
aplay: set_params:1299: Sample format non available
Available formats:
- U8
- S16_LE

```
also noting happen when using audacity ,

**Comment by Pillar1989** [comment]
aplay -Dplughw:0,0 hello.wav
